spring.application.name=basketball-predictor
spring.datasource.url=jdbc:postgresql://localhost:5432/basketball_predictor
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update